# Generated by Django 5.0.7 on 2024-09-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filme",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
