# Generated by Django 5.0.7 on 2024-09-03 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_alter_filme_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="favoritado_por",
            field=models.ManyToManyField(
                blank=True, related_name="filmes_favoritos", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
